config/routes.rb
TprLebanon::Application.routes.draw do

  resources :students

  resources :leads

  root :to => 'home#index'

  get 'home/index'
  put 'home/contact'
  get 'home/contact'
  put 'home/thanks'
  get 'home/thanks'
  put 'home/soon'
  get 'home/soon'
  get '/sat/index' => 'courses#sat'
  get '/sat/test' => 'courses#test'

end

app/models/lead.rb
class Lead < ActiveRecord::Base
end

app/models/student.rb
class Student < ActiveRecord::Base

  attr_writer :current_step

  validates_presence_of :first_name, :if => lambda { |o| o.current_step == "first" }  

  def current_step
    @current_step || steps.first
  end

COURSES = ['SAT', 'TOEFL']

  def steps
    %w[first second]
  end

  def next_step
    self.current_step = steps[steps.index(current_step)+1]
  end

  def previous_step
    self.current_step = steps[steps.index(current_step)-1]
  end

  def first_step?
    current_step == steps.first
  end

  def last_step?
    current_step == steps.last
  end

  def all_valid?
  steps.all? do |step|
    self.current_step = step
    valid?
  end
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/courses_controller.rb
class CoursesController < ActionController::Base
  protect_from_forgery
end

app/controllers/home_controller.rb
class HomeController < ActionController::Base
  protect_from_forgery

  def index
    @lead = Lead.new
    session[:web_lead_params] = {}
    session[:web_lead_params]['id'] = @lead.id
  end

  def soon
    @lead = Lead.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @lead }
    end
  end

end

app/controllers/leads_controller.rb
class LeadsController < ApplicationController

  http_basic_authenticate_with :name => "mahmoud", :password => "coudsi", :only => :index

  # GET /leads
  # GET /leads.json
  def index
    @leads = Lead.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @leads }
    end
  end

  # GET /leads/1
  # GET /leads/1.json
  def show
    @lead = Lead.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @lead }
    end
  end

  # GET /leads/new
  # GET /leads/new.json
  def new
    @lead = Lead.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @lead }
    end
  end

  # GET /leads/1/edit
  def edit
    @lead = Lead.find(params[:id])
  end

  # POST /leads
  # POST /leads.json
  def create
    @lead = Lead.new(params[:lead])

    respond_to do |format|
      if @lead.save
        format.html { redirect_to @lead, notice: 'Lead was successfully created.' }
        format.json { render json: @lead, status: :created, location: @lead }
      else
        format.html { render action: "new" }
        format.json { render json: @lead.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /leads/1
  # PUT /leads/1.json
  def update
    @lead = Lead.find(params[:id])

    respond_to do |format|
      if @lead.update_attributes(params[:lead])
        format.html { redirect_to "/home/thanks", notice: 'Lead was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @lead.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /leads/1
  # DELETE /leads/1.json
  def destroy
    @lead = Lead.find(params[:id])
    @lead.destroy

    respond_to do |format|
      format.html { redirect_to leads_url }
      format.json { head :ok }
    end
  end
end

app/controllers/student_steps_controller.rb
class StudentStepsController < ApplicationController
end

app/controllers/students_controller.rb
class StudentsController < ApplicationController
  # GET /students
  # GET /students.json
  def index
    @students = Student.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @students }
    end
  end

  # GET /students/1
  # GET /students/1.json
  def show
    @student = Student.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @student }
    end
  end

  # GET /students/new
  # GET /students/new.json
  def new
    session[:students_params] ||= {}
    @student = Student.new(session[:students_params])
    @student.current_step = session[:student_step]

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @student }
    end
  end

  # GET /students/1/edit
  def edit
    @student = Student.find(params[:id])
  end

  # POST /students
  # POST /students.json
  def create
    session[:students_params].deep_merge!(params[:student]) if params[:student]
    @student = Student.new(session[:students_params])
    @student.current_step = session[:student_step]
    if @student.valid?
      if params[:back_button]
        @student.previous_step
      elsif @student.last_step?
        @student.save if @student.all_valid?
      else
        @student.next_step
      end
      session[:student_step] = @student.current_step
    end
    if @student.new_record?
      render "new"
    else
      session[:student_step] = session[:students_params] = nil
      flash[:notice] = "Student saved!"
      redirect_to @student
    end
  end

  # PUT /students/1
  # PUT /students/1.json
  def update
    @student = Student.find(params[:id])

    respond_to do |format|
      if @student.update_attributes(params[:student])
        format.html { redirect_to @student, notice: 'Student was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @student.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /students/1
  # DELETE /students/1.json
  def destroy
    @student = Student.find(params[:id])
    @student.destroy

    respond_to do |format|
      format.html { redirect_to students_url }
      format.json { head :ok }
    end
  end
end

app/controllers/students_controller_org.rb
class StudentsController < ApplicationController
  # GET /students
  # GET /students.json
  def index
    @students = Student.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @students }
    end
  end

  # GET /students/1
  # GET /students/1.json
  def show
    @student = Student.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @student }
    end
  end

  # GET /students/new
  # GET /students/new.json
  def new
    @student = Student.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @student }
    end
  end

  # GET /students/1/edit
  def edit
    @student = Student.find(params[:id])
  end

  # POST /students
  # POST /students.json
  def create
    @student = Student.new(params[:student])

    respond_to do |format|
      if @student.save
        format.html { redirect_to @student, notice: 'Student was successfully created.' }
        format.json { render json: @student, status: :created, location: @student }
      else
        format.html { render action: "new" }
        format.json { render json: @student.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /students/1
  # PUT /students/1.json
  def update
    @student = Student.find(params[:id])

    respond_to do |format|
      if @student.update_attributes(params[:student])
        format.html { redirect_to @student, notice: 'Student was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @student.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /students/1
  # DELETE /students/1.json
  def destroy
    @student = Student.find(params[:id])
    @student.destroy

    respond_to do |format|
      format.html { redirect_to students_url }
      format.json { head :ok }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/leads_helper.rb
module LeadsHelper
end

app/helpers/student_steps_helper.rb
module StudentStepsHelper
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/views/courses/sat.html.erb
<link href="http://fonts.googleapis.com/css?family=Arvo" rel="stylesheet" type="text/css">
<link href="//netdna.bootstrapcdn.com/font-awesome/4.0.1/css/font-awesome.css" rel="stylesheet">
<style>
body {
font-size: 14px;
color: black;
}
a {
color: white;
text-decoration: underline;
}
.pricing-column li {
height: 40px;
}
li div {
    height:40px;
    display:table-cell;
    vertical-align : middle;
    width: 375px;
}
</style>

<% if false %><a href="#more" class="down-tab">Click to learn more about the SAT <i class="fa fa-arrow-down"></i></a><% end %>
<section class="slider">
    <div class="container homeslider">
        <div class="well homeslider">
            <div id="myCarousel" class="carousel slide carousel-fade">
                <div class="carousel-inner">
                  <div class="active item">
                        <img class="carousel" src="../images/sat/ultimate.jpg" height="25%" width="100%">
                        <div class="carousel-caption">
                          <h1 class="caption">Ultimate Course | Our Most Popular Comprehensive Prep</h1>
                          <p class="caption">
                            Master your exam with the most comprehensive prep course. We'll review all the content, teach you our exclusive strategies and ensure you're completely prepared with extensive in-class practice. Ultimate delivers 30 hours of live instruction and 4 practice tests, plus essential insider admissions advice.
                          </p>
                        </div>
                  </div>
                  <div class="item">
                        <img class="carousel" src="../images/sat/honor.jpg" height="25%" width="100%">
                        <div class="carousel-caption">
                          <h1 class="caption">SAT Honors</h1>
                          <p class="caption">
                            This Intensive Prep is designed for top-scoring students and is taught by the best Princeton Review instructors. This prestigious program offers 60 hours of intensive prep covering an advanced curriculum. We'll go over all content tested, teach you our exclusive strategies and review practice questions in class. A minimum starting score of 1850 is required for admission.
                          </p>
                        </div>
                  </div>
                  <div class="item">
                        <img class="carousel" src="../images/sat/private.jpg" height="25%" width="100%">
                        <div class="carousel-caption">
                          <h1 class="caption">Private Tutoring</h1>
                          <p class="caption">
                            This is our most personalized offering with the greatest flexibility. Our private tutoring programs are completely customized to your needs, goals, schedule and learning style. 
                            </p>
                        </div>
                  </div>
                </div>
                <a class="carousel-control left" href="#myCarousel" data-slide="prev"><i class="icon-chevron-left"></i></a>
                <a class="carousel-control right" href="#myCarousel" data-slide="next"><i class="icon-chevron-right"></i></a>
            </div>
        </div>
    </div>
</section>

<div class="quickfacts">
  <h1 class="facts">
    SAT - Quick Facts
  </h1>
    <div class="row">
      <div class="span4">
        <strong>Frequency:</strong> 6 times/year<br/>
        <strong>Duration:</strong> 3 hours, 45 minutes<br/>
        <strong>Section:</strong> Math, Critical Reading, Writing<br/>
      </div>
      <div class="span5">
        <strong>Cost:</strong> $86 (international fee)<br/>
        <strong>Max Score:</strong> 800 per section<br/>
        <strong>Average Score:</strong> Math: 516 - Critical Reading: 501 - Writing: 492<br/>
      </div>
    </div>
</div>

<div class="accordion" id="accordion1">
    <div class="accordion-group">
        <div class="accordion-heading">
            <a class="accordion-toggle" data-toggle="collapse" data-parent="#accordion1" href="#collapseOne">
                <center>More Information</center>
            </a>
        </div>
        <div id="collapseOne" class="accordion-body collapse">
            <div class="accordion-inner">
              <div class="accordion sub" id="accordion2">
                <div class="accordion-group sub">
                  <div class="accordion-heading sub">
                    <a class="accordion-toggle sub" data-toggle="collapse" data-parent="#accordion2" href="#collapseTwo">
                      What is the SAT and why is it important?
                    </a>
                  </div>
                  <div id="collapseTwo" class="accordion-body sub collapse">
                    <div class="accordion-inner sub">
                      Created by The College Board, the SAT is an entrance exam used by most colleges and universities to make admissions decisions. The idea (in theory, at least) is to provide colleges with one common criterion that can be used to compare all applicants. However, it is just one factor in the admissions decision. Schools also consider your high school GPA, academic transcript, letters of recommendation, interviews and personal essays. The weight placed on SAT scores varies from school to school. For more specific information on the importance of SAT scores at the schools you're interested in, contact the admissions offices directly. 
                    </div>
                  </div>
                </div>
                <div class="accordion-group sub">
                  <div class="accordion-heading sub">
                    <a class="accordion-toggle sub" data-toggle="collapse" data-parent="#accordion2" href="#collapseThree">
                      When is the SAT offered?
                    </a>
                  </div>
                  <div id="collapseThree" class="accordion-body sub collapse">
                    <div class="accordion-inner sub">
                      The SAT is offered every year in October, November, December, January, May and June.
                    </div>
                  </div>
                </div>
                <div class="accordion-group sub">
                  <div class="accordion-heading sub">
                    <a class="accordion-toggle sub" data-toggle="collapse" data-parent="#accordion2" href="#collapseFour">
                      What specifically does the SAT test?
                    </a>
                  </div>
                  <div id="collapseFour" class="accordion-body sub collapse">
                    <div class="accordion-inner sub">
                      There are three SAT sections: Math, Critical Reading and Writing. The Writing section requires test takers to complete an essay that is factored into the final score. The writing section also includes 49 multiple-choice grammar questions. Start to finish, the test will take you three hours and 45 minutes.
                    </div>
                  </div>
                </div>
                <div class="accordion-group sub">
                  <div class="accordion-heading sub">
                    <a class="accordion-toggle sub" data-toggle="collapse" data-parent="#accordion2" href="#collapseFive">
                      How is the SAT scored?
                    </a>
                  </div>
                  <div id="collapseFive" class="accordion-body sub collapse">
                    <div class="accordion-inner sub">
                      Each section is scored on a 200- to 800-point scale, making the "perfect" score 2400.
                    </div>
                  </div>
                </div>
                <div class="accordion-group sub">
                  <div class="accordion-heading sub">
                    <a class="accordion-toggle sub" data-toggle="collapse" data-parent="#accordion2" href="#collapseSix">
                      How do I register?
                    </a>
                  </div>
                  <div id="collapseSix" class="accordion-body sub collapse">
                    <div class="accordion-inner sub">
                      SAT registration deadlines fall approximately five weeks before each test date. You can register online at the <a href ="http://sat.collegeboard.org/register/sat-international-dates" target="_blank">College Board website</a>
                    </div>
                  </div>
                </div>
                <div class="accordion-group sub">
                  <div class="accordion-heading sub">
                    <a class="accordion-toggle sub" data-toggle="collapse" data-parent="#accordion2" href="#collapseSeven">
                      How do I prepare?
                    </a>
                  </div>
                  <div id="collapseSeven" class="accordion-body sub collapse">
                    <div class="accordion-inner sub">
                      We can help. We have prep solutions for every student and every budget. Check out the different prep options we have for the SAT below.
                    </div>
                  </div>
                </div>
              </div>
            </div>
        </div>
    </div>
</div>

<div class="pricing-table-wrapper">
  <div class="pricing-table row-fluid">
      <ul class="pricing-column span4">
          <li class="pricing-title"><div>ULTIMATE COURSE</div></li>
          <li class="pricing-sectiontitle"><div>Course Benefits</div></li>
          <li><div>The most comprehensive prep</div></li>
          <li><div>Highly trained and charismatic teachers</div></li>
          <li><div>In-class mastery with<br/> extensive practice and drills</div></li>
          <li class="pricing-sectiontitle"><div>Course Features</div></li>
          <li><div>30 hours of in-class instruction</div></li>
          <li><div>4 proctored practice tests and 15 additional tests</div></li>
          <li><div>Study Tools: Access to our SAT Self-Paced courses with 40-60 hours of video lessons</div></li>
          <li><div>Extra Help: Interactive Admissions and Financial Aid courses</div></li>
          <li><div>Guarantee: 150-point score-improvement guarantee</div></li>
          <li class="pricing-button">
            <div>
              <a class="button" href="/leads/new">Register</a>
            </div>
          </li>
      </ul>
      <ul class="pricing-column span4">
          <li class="pricing-title"><div>SAT HONORS</div></li>
          <li class="pricing-sectiontitle"><div>Course Benefits</div></li>
          <li><div>A guaranteed score of 2100 or higher on the SAT</div></li>
          <li><div>Prep with our most experienced and successful instructors</div></li>
          <li><div>The most classroom hours you can get with a Princeton Review expert</div></li>
          <li class="pricing-sectiontitle"><div>Course Features</div></li>
          <li><div>60 hours of in-class instruction</div></li>
          <li><div>5 proctored practice tests and 15 additional tests</div></li>
          <li><div>Study Tools: Access to 20-30 hours of additional video lessons</div></li>
          <li><div>Extra Help: Interactive Admissions and Financial Aid courses</div></li>
          <li><div>Guarantee: Score 2100 or higher on the SAT or get your money back</div></li>
          <li class="pricing-button">
            <div>
              <a class="button" href="/leads/new">Register</a>
            </div>
          </li>
      </ul>
      <ul class="pricing-column span4">
          <li class="pricing-title"><div>Private Tutoring</div></li>
          <li class="pricing-sectiontitle"><div>Course Benefits</div></li>
          <li><div>The freedom to meet at the time you want</div></li>
          <li><div>A tutor with the skills and style to best meet your needs</div></li>
          <li><div>A plan to help you get into your top-choice schools</div></li>
          <li class="pricing-sectiontitle"><div>Course Features</div></li>
          <li><div>A custom prep plan designed by an elite tutor</div></li>
          <li><div>4 core practice SATs and 17 additional exams<br/><br/></div></li>
          <li><div>Frequent adjustments to match your progress<br/><br/></div></li>
          <li><br><br/></li>
          <li><br><br/></li>
          <li class="pricing-button">
            <div>
              <a class="button" href="/leads/new">Register</a>
            </div>
          </li>
      </ul>
  </div>
</div>

<div class="diagnostic">
  <center>
    <h1 class="diagnostic">Free Practice Test</h1>
    <p class="diagnostic">To encourage you to get started,<br/>
      we are offering free practice tests.
    </p><br/>
    <a class="btn-large btn-info" href="/leads/new">Start here</a><br/><br/><br/>
  </center>
</div>

app/views/courses/test.html.erb
Hello

app/views/layouts/application.html.erb
<script type="text/javascript">

  var _gaq = _gaq || [];
  _gaq.push(['_setAccount', 'UA-43872725-1']);
  _gaq.push(['_trackPageview']);

  (function() {
    var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
    ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
  })();

</script>

<%= yield %>

app/views/layouts/courses.html.erb
<!DOCTYPE html>
<html lang="en">
    <head>
        <!-- Basic Needs -->
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>The Princeton Review Lebanon</title>   

        <link href="../css_template/bootstrap.css" rel="stylesheet">
        <link href="../css_template/bootstrap-responsive.css" rel="stylesheet">
        <link href="../css_template/style.css" rel="stylesheet">
        <link href="../css_template/font-awesome.css" rel="stylesheet">
        <link href="../css_template/animate.css" rel="stylesheet">
        <link href="../css_template/prettyPhoto.css" rel="stylesheet">

        <%= csrf_meta_tags %>

        <style type="text/css">  
          body { padding-top: 0px; }
        </style>  

        <!-- Fonts -->
    <link href = 'http://fonts.googleapis.com/css?family=Open+Sans:400,400italic,600,800' rel = 'stylesheet' type = 'text/css'>
    
        <!-- Favicon Icon -->
    <link rel="shortcut icon" href="../ico/favicon.png">

        <!-- HTML5 shim, for IE6-8 support of HTML5 elements -->
        <!--[if lt IE 9]>
            <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
        <![endif]-->
    </head>
    <body>
        <!-- Start header -->
        <header class="header">
            <div class="container">
                <div class="navbar">
                    <div class="navbar-inner">
                        <div class="brand-wrapper">
                          <a class="brand" href="/"><img src="../images/reviewlogo.png" class="logo"></a>
                        </div>
                          <ul class="nav">
                            <li><%= link_to "SAT", '/sat/index' %></li>
                            <li><%= link_to "TOEFL", '/home/soon' %></li>
                            <li><%= link_to "GMAT", '/home/soon' %></li>
                            <li><%= link_to "GRE", '/home/soon' %></li>
                            <li><%= link_to "MCAT", '/home/soon' %></li>
                            <li><%= link_to "USMLE", '/home/soon' %></li>
                          </ul>
                    </div>
                </div>
            </div>
        </header>
        <!-- End header -->
        <!-- Start page header -->              
        <!-- End page header -->   
        <!-- Start Yield -->
            <div class="container">
                <div class="row">
                    <div class="span12">
                      <%= yield %>
                    </div>
                </div>
            </div>
        <!-- End Yield -->
        <!-- Start socket -->
        <section class="socket">
            <div class="container">
                <div class="row">
                    <div class="span6">
                        <span>© 2013 The Princeton Revirew Lebanon. All rights reserved. Authorized Users only.</span>     
                    </div>
                </div>     
            </div>
        </section>
      <%= yield :scripts %>
        <!-- End socket -->
        <!-- Le javascript
        ================================================== -->
        <!-- Placed at the end of the document so the pages load faster -->
        <script src="../js/jquery-1.8.3.js"></script>
        <script src="../js/bootstrap.min.js"></script>
        <script src="../js/jquery.onecarousel.min.js"></script>
        <script src="../js/jquery.tweet.js"></script>
        <script src="../js/jflickrfeed.min.js"></script>
        <script src="../js/jquery.prettyPhoto.js"></script>
        <script src="../js/jquery.fitvids.js"></script>
        <script src="../js/jquery.isotope.min.js"></script>
        <script src="../js/random.js"></script>
    </body>
</html>

app/views/layouts/students.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "TprLebanon" %></title>
    <%= csrf_meta_tags %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js" type="text/javascript"></script>
    <![endif]-->

    <%= stylesheet_link_tag "application", :media => "all" %>

    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    <%= favicon_link_tag 'images/apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
    <%= favicon_link_tag 'images/apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
    <%= favicon_link_tag 'images/apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
    <%= favicon_link_tag 'images/apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>
  </head>
  <body>

    <div class="navbar navbar-fluid-top">
      <div class="navbar-inner">
        <div class="container-fluid">
          <a class="btn btn-navbar" data-target=".nav-collapse" data-toggle="collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </a>
          <a class="brand" href="#"><img src="http://www.princetonreviewlebanon.com/images/logo_white.png"></a>
          <div class="container-fluid nav-collapse">
            <ul class="nav">
              <li><%= link_to "Link1", "/path1"  %></li>
              <li><%= link_to "Link2", "/path2"  %></li>
              <li><%= link_to "Link3", "/path3"  %></li>
            </ul>
          </div><!--/.nav-collapse -->
        </div>
      </div>
    </div>

    <div class="container-fluid">
      <div class="row-fluid">
        <div class="span3">
          <div class="well sidebar-nav">
            <ul class="nav nav-list">
              <li class="nav-header">Sidebar</li>
              <li><%= link_to "Link1", "/path1"  %></li>
              <li><%= link_to "Link2", "/path2"  %></li>
              <li><%= link_to "Link3", "/path3"  %></li>
            </ul>
          </div><!--/.well -->
        </div><!--/span-->
        <div class="span9">
          <%= bootstrap_flash %>
          <%= yield %>
        </div>
      </div><!--/row-->

      <footer>
        <p>&copy; Company 2013</p>
      </footer>

    </div> <!-- /container -->

    <!-- Javascripts
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <%= javascript_include_tag "application" %>

  </body>
</html>

app/views/students/_first_step.html.erb
  <%= f.input :first_name %>
  <%= f.input :last_name %>
  <%= f.input :course_of_interest, collection: Student::COURSES, :prompt => "Course of interest...", :name => "course" %>
  <%= f.input :phone_home %>
  <%= f.input :phone_cell %>
  <%= f.input :email %>

app/views/students/_form.html.erb
<%= simple_form_for @student, :html => { :class => 'form-horizontal' } do |f| %>
  <%= f.input :first_name %>
  <%= f.input :last_name %>
  <%= f.input :course_of_interest, collection: Student::COURSES, :prompt => "Course of interest..." %>
  <%= f.input :phone_home %>
  <%= f.input :phone_cell %>
  <%= f.input :email %>
  <%= f.input :current_institution %>
  <%= f.input :source %>
  <%= f.input :target_institution %>
  <%= f.input :previous_score1 %>
  <%= f.input :previous_score2 %>
  <%= f.input :previous_score3 %>
  <%= f.input :previous_score_total %>
  <%= f.input :target_score1 %>
  <%= f.input :target_score2 %>
  <%= f.input :target_score3 %>
  <%= f.input :target_score_total %>

  <div class="form-actions">
    <%= f.button :submit, :class => 'btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                students_path, :class => 'btn' %>
  </div>

<% end %>

app/views/students/index.html.erb
<%- model_class = Student -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:first_name) %></th>
      <th><%= model_class.human_attribute_name(:last_name) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @students.each do |student| %>
      <tr>
        <td><%= link_to student.id, student_path(student) %></td>
        <td><%= student.first_name %></td>
        <td><%= student.last_name %></td>
        <td><%=l student.created_at %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_student_path(student), :class => 'btn btn-mini' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      student_path(student),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-mini btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_student_path,
            :class => 'btn btn-primary' %>